### ISSUE TITLE
Blank website after upgrade to snappymail 2.36.3~ynh4

### ISSUE THREAD

**Issue by moses-69** [YunoHost-Apps/snappymail_ynh#168]
### Describe the bug

After upgrading to version 2.36.3~ynh4 only a blank screen is shown when opening the website of snappymail on my server .

### Context

- Hardware: VPS bought online
- YunoHost version: 11.2.27
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- If upgrading, current package version: *2.36.3~ynh4*

### Steps to reproduce

     `sudo yunohost tools upgrade apps`

No error message, but warning:
```
Info: Updating database...
Info: [++++................] > Ensuring downward compatibility...
Info: [####++++............] > Upgrading source files...
Warning: realpath: /var/cache/yunohost/app_tmp_work_dirs/app_9aa3df48/patches/main: No such file or directory
Info: [########++++........] > Upgrading system configurations related to snappymail...
Info: [############++++....] > Applying SSO patch...
Info: [####################] > Upgrade of snappymail completed
Success! snappymail upgraded
Success! Upgrade complete

```

**Comment by ballinger** [comment]
same

**Comment by rmueck** [comment]
Same here! 
log looks fine:

~~~
# yunohost tools upgrade apps
Info: Now upgrading snappymail…
Info: Creating a safety backup prior to the upgrade
Info: Collecting files to be backed up for snappymail…
Info: Declaring files to be backed up...
Info: Backup script completed for snappymail. (YunoHost will then actually copy those files to the archive).
Info: Creating a backup archive from the collected files…
Info: The archive will contain about 13.2MB of data.
Success! Backup created: snappymail-pre-upgrade2
Success! Backup deleted: snappymail-pre-upgrade1
Info: Updating sources...
Info: Updating system_user...
Info: Updating install_dir...
Info: Updating permissions...
Info: Updating apt...
Info: Updating database...
Info: [++++................] > Ensuring downward compatibility...
Info: [####++++............] > Upgrading source files...
Warning: realpath: /var/cache/yunohost/app_tmp_work_dirs/app_ljgcwumm/patches/main: No such file or directory
Info: [########++++........] > Upgrading system configurations related to snappymail...
Info: [############++++....] > Applying SSO patch...
Info: [####################] > Upgrade of snappymail completed
Success! snappymail upgraded
Success! Upgrade complete
~~~

Get error 500

I found the following in the logs after upgrade:


~~~
/var/log/nginx/myserver.de-error.log

2024/08/09 09:07:28 [crit] 225311#225311: *25836 stat() "/var/www/snappymail/app/" failed (13: Permission denied), client: 2.241.130.148, server: myserver.de, request: "POST /snappymail/app/?/Json/&q[]=/0/ HTTP/2.0", host: "myserver.de"
2024/08/09 09:07:28 [crit] 225311#225311: *25836 stat() "/var/www/snappymail/app/" failed (13: Permission denied), client: 2.241.130.148, server: myserver.de, request: "POST /snappymail/app/?/Json/&q[]=/0/ HTTP/2.0", host: "myserver.de"
2024/08/09 09:07:28 [crit] 225311#225311: *25836 stat() "/var/www/snappymail/app/" failed (13: Permission denied), client: 2.241.130.148, server: myserver.de, request: "POST /snappymail/app/?/Json/&q[]=/0/ HTTP/2.0", host: "myserver.de"
2024/08/09 09:07:28 [crit] 225311#225311: *25836 stat() "/var/www/snappymail/app/" failed (13: Permission denied), client: 2.241.130.148, server: myserver.de, request: "POST /snappymail/app/?/Json/&q[]=/0/ HTTP/2.0", host: "myserver.de"
2024/08/09 09:10:11 [error] 231048#231048: *25855 FastCGI sent in stderr: "PHP message: PHP Warning:  mkdir(): Permission denied in /var/www/snappymail/app/snappymail/v/2.36.4/setup.php on line 82; PHP message: PHP Warning:  file_put_contents(/var/www/snappymail/app/data/_data_/_default_/.htaccess): Failed to open stream: Permission denied in /var/www/snappymail/app/snappymail/v/2.36.4/setup.php on line 83; PHP message: PHP Warning:  mkdir(): Permission denied in /var/www/snappymail/app/snappymail/v/2.36.4/setup.php on line 95; PHP message: PHP Warning:  mkdir(): Permission denied in /var/www/snappymail/app/snappymail/v/2.36.4/setup.php on line 95; PHP message: PHP Warning:  mkdir(): Permission denied in /var/www/snappymail/app/snappymail/v/2.36.4/setup.php on line 95; PHP message: PHP Warning:  mkdir(): Permission denied in /var/www/snappymail/app/snappymail/v/2.36.4/setup.php on line 95; PHP message: PHP Warning:  mkdir(): Permission denied in /var/www/snappymail/app/snappymail/v/2.36.4/app/libraries/RainLoop/Utils.php on line 154; PHP message: PHP Fatal error:  Uncaught RuntimeException: Failed to create directory "/var/www/snappymail/app/data/_data_/_default_/configs" in /var/www/snappymail/app/snappymail/v/2.36.4/app/libraries/RainLoop/Utils.php:155
Stack trace:
#0 /var/www/snappymail/app/snappymail/v/2.36.4/app/libraries/RainLoop/Config/AbstractConfig.php(315): RainLoop\Utils::saveFile()
#1 /var/www/snappymail/app/snappymail/v/2.36.4/app/libraries/RainLoop/Config/Application.php(161): RainLoop\Config\AbstractConfig->Save()
#2 /var/www/snappymail/app/snappymail/v/2.36.4/app/libraries/RainLoop/Config/AbstractConfig.php(248): RainLoop\Config\Application->Save()
#3 /var/www/snappymail/app/snappymail/v/2.36.4/app/libraries/RainLoop/Config/Application.php(19): RainLoop\Config\AbstractConfig->Load()
#4 /var/www/snappymail/app/snappymail/v/2.36.4/app/libraries/RainLoop/Api.php(23): RainLoop\Config\Application->Load()
#5 /var/www/snappymail/app/snappymail/v/2.36.4/app/libraries/RainLoop/Actions.php(116): RainLoop\A
2024/08/09 09:12:17 [error] 231048#231048: *25855 FastCGI sent in stderr: "PHP message: PHP Warning:  mkdir(): Permission denied in /var/www/snappymail/app/snappymail/v/2.36.4/setup.php on line 82; PHP message: PHP Warning:  file_put_contents(/var/www/snappymail/app/data/_data_/_default_/.htaccess): Failed to open stream: Permission denied in /var/www/snappymail/app/snappymail/v/2.36.4/setup.php on line 83; PHP message: PHP Warning:  mkdir(): Permission denied in /var/www/snappymail/app/snappymail/v/2.36.4/setup.php on line 95; PHP message: PHP Warning:  mkdir(): Permission denied in /var/www/snappymail/app/snappymail/v/2.36.4/setup.php on line 95; PHP message: PHP Warning:  mkdir(): Permission denied in /var/www/snappymail/app/snappymail/v/2.36.4/setup.php on line 95; PHP message: PHP Warning:  mkdir(): Permission denied in /var/www/snappymail/app/snappymail/v/2.36.4/setup.php on line 95; PHP message: PHP Warning:  mkdir(): Permission denied in /var/www/snappymail/app/snappymail/v/2.36.4/app/libraries/RainLoop/Utils.php on line 154; PHP message: PHP Fatal error:  Uncaught RuntimeException: Failed to create directory "/var/www/snappymail/app/data/_data_/_default_/configs" in /var/www/snappymail/app/snappymail/v/2.36.4/app/libraries/RainLoop/Utils.php:155
Stack trace:
#0 /var/www/snappymail/app/snappymail/v/2.36.4/app/libraries/RainLoop/Config/AbstractConfig.php(315): RainLoop\Utils::saveFile()
#1 /var/www/snappymail/app/snappymail/v/2.36.4/app/libraries/RainLoop/Config/Application.php(161): RainLoop\Config\AbstractConfig->Save()
#2 /var/www/snappymail/app/snappymail/v/2.36.4/app/libraries/RainLoop/Config/AbstractConfig.php(248): RainLoop\Config\Application->Save()
#3 /var/www/snappymail/app/snappymail/v/2.36.4/app/libraries/RainLoop/Config/Application.php(19): RainLoop\Config\AbstractConfig->Load()
#4 /var/www/snappymail/app/snappymail/v/2.36.4/app/libraries/RainLoop/Api.php(23): RainLoop\Config\Application->Load()
#5 /var/www/snappymail/app/snappymail/v/2.36.4/app/libraries/RainLoop/Actions.php(116): RainLoop\A
~~~

**Comment by Tagadda** [comment]
Titus made some changes recently (#169). Can you try to force the upgrade again ?
`sudo yunohost app upgrade snappymail --force`
